### PR TITLE
feat: support route like 'user.register'.

### PR DESCRIPTION
**Pull request by dmoosocool**
In my project i need supported route like `user.register`.

Please confirm if this PR is necessary.

How can I support such routing if not needed?

### CODE REVIEW

**Comment by ktsn** [comment]
Can you explain your use case a bit more? What problem does this change solve?

**Comment by dmoosocool** [comment]
> Can you explain your use case a bit more? What problem does this change solve?

i used `vue-auto-routing` plugin, 

i want to support route like `user.register`, when i create `pages/user.register.vue`, the plugin generate route file: 
```js
...
function User() {
  return import(/* webpackChunkName: "page-user" */ '@/pages/user.register.vue')
}
...

export default [
...
  {
    name: 'user',
    path: 'user',
    component: User
  }
]
```

but what i need is: 

```js
...
function User() {
  return import(/* webpackChunkName: "page-user" */ '@/pages/user.register.vue')
}
...

export default [
...
  {
    name: 'user',
    path: 'user.register',
    component: User
  }
]
```

**Comment by dmoosocool** [comment]
> In my unit test case, this rule ignores all strings after the first "."
```js
function basename(filename: string): string {
  return filename.replace(/\..+?$/, '') 
}
basename('user.register.vue'); // output: user,
```

so i changed this regex.

```js
function basename(filename: string): string {
  return filename.replace(/\.[^.]+$/g, '') 
}
basename('user.register.vue'); // output: user.register,
```

> my test project folder
```
pages
├── 404.vue
├── about.vue
├── index.vue
└── user.register.vue
```

> vue.config.js
```js
pluginOptions: {
    autoRouting: {
      chunkNamePrefix: 'LichUI-'
    },
}
```


> and my unit test case output: 

`pathToMapPath` to call `return segments.slice(0, -1).concat(basename(last));` // return: `404`
`pathToMapPath` to call `return segments.slice(0, -1).concat(basename(last));` // return: `about`
`pathToMapPath` to call `return segments.slice(0, -1).concat(basename(last));` // return: `index`
`pathToMapPath` to call `return segments.slice(0, -1).concat(basename(last));` // return: `user.register`
`pathToName` to call `segments = segments.slice(0, -1).concat(basename(last));` // segements: `404`
`pathToName` to call `segments = segments.slice(0, -1).concat(basename(last));` // segements: `404`
`toActualPath` to call `const last = basename(segments[lastIndex]);` // last: `404`
`toActualPath` to call `const last = basename(segments[lastIndex]);` // last: `404`
`pathToName` to call `segments = segments.slice(0, -1).concat(basename(last));` // segements: `about`
`pathToName` to call `segments = segments.slice(0, -1).concat(basename(last));` // segements: `about`
`toActualPath` to call `const last = basename(segments[lastIndex]);` // last: `about`
`toActualPath` to call `const last = basename(segments[lastIndex]);` // last: `about`
`pathToName` to call `segments = segments.slice(0, -1).concat(basename(last));` // segements: `index`
`pathToName` to call `segments = segments.slice(0, -1).concat(basename(last));` // segements: `index`
`toActualPath` to call `const last = basename(segments[lastIndex]);` // last: `index`
`toActualPath` to call `const last = basename(segments[lastIndex]);` // last: `index`
`pathToName` to call `segments = segments.slice(0, -1).concat(basename(last));` // segements: `user.register`
`pathToName` to call `segments = segments.slice(0, -1).concat(basename(last));` // segements: `user.register`
`toActualPath` to call `const last = basename(segments[lastIndex]);` // last: `user.register`
`toActualPath` to call `const last = basename(segments[lastIndex]);` // last: `user.register`

> and the `vue-auto-routing` plugin generate `index.js`
```js
function Index() {
  return import(/* webpackChunkName: "LichUI-index" */ '@/pages/index.vue')
}
function _404() {
  return import(/* webpackChunkName: "LichUI-404" */ '@/pages/404.vue')
}
function About() {
  return import(/* webpackChunkName: "LichUI-about" */ '@/pages/about.vue')
}
function UserRegister() {
  return import(
    /* webpackChunkName: "LichUI-user.register" */ '@/pages/user.register.vue'
  )
}

export default [
  {
    name: 'index',
    path: '',
    component: Index,
    meta: {
      requiresAuth: true,
      title: 'hello lichui'
    }
  },
  {
    name: '404',
    path: '404',
    component: _404
  },
  {
    name: 'about',
    path: 'about',
    component: About
  },
  {
    name: 'user.register',
    path: 'user.register',
    component: UserRegister
  }
]
```

it works for me.

**Comment by ktsn** [comment]
That makes sense. Can we add a test case for it?

**Comment by dmoosocool** [comment]
> That makes sense. Can we add a test case for it?

ok, it's completed, thanks.

**Pull request merged**
